docs: detail requirements for manual azure batch pools
seqeralabs/docs pull request #21
Opened 2024-04-12 09:04 UTC by adamrtalbot

The workaround for Azure Batch pools did not indicate the requirements these pools had to meet. This PR references the Nextflow docs for Azure Batch named pools.

2024-04-15 13:12 UTC, justinegeffen approved these changes
Looks good from an editorial point of view. Added Ben for technical review.

2024-04-15 13:21 UTC, bentsherman approved these changes

2024-04-15 13:26 UTC, pditommaso requested changes

2024-04-15 13:26 UTC, pditommaso commented on platform_versioned_docs/version-23.3.0/faqs.mdx
> +    - **Note**: Both pools must meet the requirements of a pre-existing pool as detailed in the [Nextflow documentation](https://www.nextflow.io/docs/latest/azure.html#requirements-on-pre-existing-na
Relative link should be used instead

2024-04-15 13:27 UTC, bentsherman commented on platform_versioned_docs/version-23.3.0/faqs.mdx
> +    - **Note**: Both pools must meet the requirements of a pre-existing pool as detailed in the [Nextflow documentation](https://www.nextflow.io/docs/latest/azure.html#requirements-on-pre-existing-na
This is the seqera docs

2024-04-15 13:30 UTC, pditommaso commented on platform_versioned_docs/version-23.3.0/faqs.mdx
> +    - **Note**: Both pools must meet the requirements of a pre-existing pool as detailed in the [Nextflow documentation](https://www.nextflow.io/docs/latest/azure.html#requirements-on-pre-existing-na
Oops 👍

2024-07-09 18:07 UTC, justinegeffen commented
@adamrtalbot, I'm ready to merge this. Should the 24.1.1 docs also be updated?

2024-07-23 19:36 UTC, merged