Refining casing for Data Studios
seqeralabs/docs pull request #247
Opened 2024-10-03 14:25 UTC by justinegeffen

Refining and improving casing for Data Studios.

2024-10-15 16:08 UTC, robnewman requested changes
Just one minor fix needed, otherwise looks good.

2024-10-15 16:08 UTC, robnewman commented on platform_versioned_docs/version-24.1/data/data-studios.mdx
> +1. Select **Add** to add the new Data Studio.
This is a regression - it's not the Product. It should be "new session"

```suggestion
1. Select **Add** to add the new session.
```

2024-10-17 19:54 UTC, jason-seqera commented
I've manually applied these changes to: https://github.com/seqeralabs/docs/pull/258

2024-10-17 21:19 UTC, robnewman approved these changes

2024-10-17 21:26 UTC, jason-seqera commented
We can therefore technically close this since the other PR replaces this.

2024-10-25 17:42 UTC, closed without merging