Updates and additions to the changelog
seqeralabs/docs pull request #305
Opened 2024-11-15 19:41 UTC by justinegeffen

2024-11-18 20:44 UTC, justinegeffen reviewed
Updating dates

2024-11-18 20:44 UTC, justinegeffen commented on changelog/seqera-enterprise/v23.4.0.mdx
> +date: 2024-01-11
```suggestion
date: 2024-08-02
```

2024-11-18 20:44 UTC, justinegeffen commented on changelog/seqera-enterprise/v23.4.4.mdx
> +date: 2024-04-21
```suggestion
date: 2024-03-20
```

2024-11-18 20:44 UTC, justinegeffen commented on changelog/seqera-enterprise/v23.4.5.mdx
> +date: 2024-04-21
```suggestion
date: 2024-07-15
```

2024-11-18 20:44 UTC, justinegeffen commented on changelog/seqera-enterprise/v23.4.6.mdx
> +date: 2024-04-21
```suggestion
date: 2024-08-01
```

2024-11-20 20:59 UTC, justinegeffen commented
@llewellyn-sl, I'd like to merge this PR this week. Could you build your 24.2 release notes on top of these changes?

2024-11-22 08:35 UTC, christopher-hakkaart requested changes
Very minor suggestions.

2024-11-22 08:35 UTC, christopher-hakkaart commented on changelog/seqera-cloud/v24.2.0_cycle25.mdx
>  - Quick launch now accepts pipelines that do not have a branch named `master`.
```suggestion
- Quick Launch now accepts pipelines that do not have a branch named `master`.
```

2024-11-22 08:35 UTC, christopher-hakkaart commented on changelog/seqera-enterprise/v22.3_major.mdx
> +/Users/justine.geffen/docs/changelog/seqera-cloud/v24.1.0_cycle17.mdx
Your name included here

2024-11-22 08:35 UTC, christopher-hakkaart commented on changelog/seqera-enterprise/v22.3_major.mdx
> +The Tower [admin panel]../platform_versioned_docs/version-22.3/administration/overview.mdx) now provides additional user and organization management features.
```suggestion
The Tower [admin panel](../platform_versioned_docs/version-22.3/administration/overview.mdx) now provides additional user and organization management features.
```

2024-11-22 08:35 UTC, christopher-hakkaart commented on changelog/seqera-enterprise/v23.2_major.mdx
> +- Add support for Graviton architecture in AWS Batch compute environments
Some sections without full stops

2024-11-22 22:53 UTC, christopher-hakkaart approved these changes
Looks good. Nothing blocking.

2024-11-25 14:05 UTC, merged