Add Data Studio 5G overlay file system limit
seqeralabs/docs pull request #46
Opened 2024-05-06 15:44 UTC by jason-seqera

First pass, needs revisions. Request originated on Slack: https://seqera.slack.com/archives/C053KDKLEQJ/p1714947936506089

2024-05-06 15:57 UTC, robnewman requested changes

2024-05-06 15:57 UTC, robnewman commented on platform_versioned_docs/version-23.4.0/data/data-studios.mdx
> +A data studio is allocated a 5G overlay filesystem partition for installing software packages and other local configuration. If you exceed the available storage space, you cannot reliably make local
```suggestion
Currently, a data studio is allocated a 5GB overlay filesystem partition by default for installing software packages and other local configuration. This limit is irrespective of the boot disk size of the container. If you exceed the available storage space, you cannot reliably make local changes to the data studio container until you free up disk space.
```

2024-05-06 15:57 UTC, robnewman commented on platform_versioned_docs/version-23.4.0/data/data-studios.mdx
> +Each time you stop and start a data studio, an additional 5G allocation is provided. As a workaround, you can stop your data studio session, and then start the data studio again to have access to 5G
```suggestion
Each time you stop and start a data studio, an additional 5GB allocation is provided. If you are experiencing a disk size limitation, as a workaround you can stop and restart the data studio.
```

2024-05-13 13:14 UTC, jason-seqera commented
@robnewman, we've decided to follow Google Developer Style for this, so I've omitted _currently_ for consistency with that. When do we want to merge this? Thanks!

2024-05-13 15:27 UTC, robnewman approved these changes

2024-05-13 23:01 UTC, jason-seqera commented
I'm going to merge this as Rob approved this on Slack DM. Thanks!

2024-05-13 23:02 UTC, merged